-- migrate:up
CREATE TABLE tag (
  id SERIAL PRIMARY KEY,
  tagMaskId VARCHAR(30) NOT NULL,
  title VARCHAR(255) NOT NULL,
  createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE UNIQUE INDEX idx_uni_tagMaskId ON tag (tagMaskId);

-- migrate:down
DROP INDEX idx_uni_tagMaskId ON tag;
DROP TABLE IF EXISTS tag;