allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260616.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260616.1'
  - '@cloudflare/workerd-linux-64@1.20260616.1'
  - '@cloudflare/workerd-linux-arm64@1.20260616.1'
  - '@cloudflare/workerd-windows-64@1.20260616.1'
  - lucide-react@1.20.0
  - miniflare@4.20260616.0
  - workerd@1.20260616.1
  - wrangler@4.101.0
